apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- deployment.yaml
- service.yaml

images:
- name: app-express
  newName: rubemnascimento81/app-express
  newTag: d6a39b71496e2ec58314999a2854448d9784a4cc
